services:
  graphql:
    image: shop-back
    restart: always
    depends_on:
      - db
    build:
      context: ./shop-back/
      target: ${RUN_MODE}
    ports:
      - ${BACKEND_PORT}:4000
    environment:
      DATABASE_URL: ${DATABASE_URL}
    develop:
      watch:
        - path: ./src/
          action: sync
          target: /app/src/
        - path: ./node_modules/
          action: sync+restart
          target: ./node_modules/
  angular:
    image: angular
    restart: always
    build:
      context: ./angular-shop/shop/
    ports:
      - ${ANGULAR_PORT}:4200
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
volumes:
  pgdata:
